DTM_params: 10
FirstDampCoef: 5000
Plugin: libTerramechanicsPlugin_new.so
PrintStep: 1000000
PublishRate: 20
SecondDampCoef: 5000
TerrainMapFileName: /home/ruyi/catkin_ws/src/MarsSim_v2/rover_gazebo/data/simulated_terrain_data.txt
TerrainParamsNum: 7
c1: 0.5
c2: -0.3
c3: 0
c_T1: 0.214
c_d1: -0.626
c_d2: 0.308
c_d3: -0.224
enable_plugin: true
sinkage_max: 0.15
x_grids: 641
x_max: 40.0
x_min: -40.0
y_grids: 641
y_max: 40.0
y_min: -40.0
