# .yaml config file
#
# The PID gains and controller settings must be saved in a yaml file that gets loaded
# to the param server via the roslaunch file (curiosity_mars_rover_control.launch).

zhurong_mars_rover:
  # Publish all joint states -----------------------------------
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Wheel Velocity Controllers ---------------------------------------
  left_front_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: base_left_wheel_joint
    pid: {p: 10.0, i: 1.0, d: 0.0}
  right_front_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: base_right_wheel_joint
    pid: {p: 10.0, i: 1.0, d: 0.0}
  back_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: back_wheel_support_back_wheel
    pid: {p: 10.0, i: 1.0, d: 0.0}


  # Wheel Steering Position Controllers ---------------------------------------
  steer_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_back_wheel_support_joint
    pid: {p: 1.0, i: 0.00, d: 0.5}

  # Camera Controller
  # camera_support_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: base_camera_support_joint
  #   pid: {p: 1.0, i: 0.00, d: 0.5}

  # camera_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: camera_support_camera_joint
  #   pid: {p: 1.0, i: 0.00, d: 0.5}
