heightmap_name: /models/mars_terrain/heightmaps_int16/HM1.png
heightmap_path: /models/mars_terrain/heightmaps_int16
heightmap_int8_path: heightmaps_int8/
texture_path: simulation_tex/

terrain_model_save_path: /models/mars_terrain
rock_model_save_path: /models/mars_rocks_lbl
world_save_path: /worlds
launch_file: /launch/image_collect.launch

DTM_save_path: /data
DTM_save_name: simulated_terrain_data.txt

dataset_images_save_path: /results/dataset_0425

plugin_config_file: /config/TerramechanicsPluginParam.yaml

terrain_data_file: /config/terrain_data.csv

terrain_height: 0.1
terrain_length: 80
parameters_num: 7

heightmap_count: 7
rock_count: 35
texture_count: 4

terrain_classes: 1
param_0: 13600
param_1: 2259100
param_2: 0.92
param_3: 0.5
param_4: 462.3
param_5: 0.61
param_6: 0.015

camera_point_num: 100

terrain_class_file: /models/mars_terrain/whole_tex/terrain_class.npy